name: Deploy Frontend to Amazon ECR and EC2

# Prueba de contenido
on:
  push:
    branches:
      - deploy

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: innovatech-front
  EC2_INSTANCE_ID: i-09c9d70c1fcfa818a

jobs:
  build-and-deploy:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout del código
      uses: actions/checkout@v3

    - name: 2. Configurar credenciales de AWS (Academy)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: 3. Login en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: 4. Construir, etiquetar y subir imagen a ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f dockerfile-front .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: 5. Desplegar en EC2 pública vía AWS SSM
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        aws ssm send-command \
          --instance-ids "${{ env.EC2_INSTANCE_ID }}" \
          --document-name "AWS-RunShellScript" \
          --comment "Despliegue automatico del Frontend" \
          --parameters commands=[ \
            "aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY", \
            "docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG", \
            "docker stop frontend-citt || true", \
            "docker rm frontend-citt || true", \
            "docker run -d --name frontend-citt -p 80:80 --restart always $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" \
          ]